version: "3.9"
services:
    web:
        build: .
        ports:
            - "localhost:1433"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "<YourStrong@Passw0rd>"
            ACCEPT_EULA: "Y"

